package intent

import (
	"embed"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/santhosh-tekuri/jsonschema/v6"
	"gopkg.in/yaml.v3"
)

//go:embed schema/*.json
var schemaFS embed.FS

// SpecError represents a single validation failure.
type SpecError struct {
	Path    string `json:"path"`
	Kind    string `json:"kind"`    // schema|ref|duplicate|cycle|renamed_template
	Message string `json:"message"`
}

// Renamed-template detection — must match the literal first non-blank
// line written by cli.SpecInit. Em-dash is the U+2014 character; the
// templates use it intentionally to make accidental ASCII paraphrasing
// stand out.
const (
	requirementTemplateMarker = "# cairn requirement spec template \u2014 DO NOT EDIT THIS FILE."
	taskTemplateMarker        = "# cairn task spec template \u2014 DO NOT EDIT THIS FILE."

	renamedTemplateMessage = "This file appears to be a renamed scaffold template. Templates are reference-only. To start authoring specs, invoke the using-cairn skill to derive from a prose spec under docs/superpowers/specs/."
)

// Validate runs schema + referential + uniqueness checks on the bundle.
// Returns ALL errors in one pass (not fail-fast).
func Validate(b *Bundle) []SpecError {
	var errs []SpecError
	errs = append(errs, validateNoTemplateMarkers(b)...)
	errs = append(errs, validateSchemas(b)...)
	errs = append(errs, validateReferential(b)...)
	return errs
}

func validateNoTemplateMarkers(b *Bundle) []SpecError {
	var out []SpecError
	for _, r := range b.Requirements {
		if isRenamedTemplate(r.RawYAML, requirementTemplateMarker) {
			out = append(out, SpecError{
				Path:    r.SpecPath,
				Kind:    "renamed_template",
				Message: renamedTemplateMessage,
			})
		}
	}
	for _, t := range b.Tasks {
		if isRenamedTemplate(t.RawYAML, taskTemplateMarker) {
			out = append(out, SpecError{
				Path:    t.SpecPath,
				Kind:    "renamed_template",
				Message: renamedTemplateMessage,
			})
		}
	}
	return out
}

func isRenamedTemplate(raw []byte, marker string) bool {
	// First non-blank line must equal the marker exactly. Trim each line's
	// leading/trailing whitespace before compare to tolerate \r\n and stray
	// spaces, but require an exact match against the marker text.
	for _, line := range strings.Split(string(raw), "\n") {
		trim := strings.TrimSpace(line)
		if trim == "" {
			continue
		}
		return trim == marker
	}
	return false
}

func validateSchemas(b *Bundle) []SpecError {
	var out []SpecError
	reqSchema, err := compileSchema("schema/requirement.schema.json")
	if err != nil {
		return []SpecError{{Kind: "schema", Message: err.Error()}}
	}
	taskSchema, err := compileSchema("schema/task.schema.json")
	if err != nil {
		return []SpecError{{Kind: "schema", Message: err.Error()}}
	}
	for _, r := range b.Requirements {
		if errs := validateOne(reqSchema, r.RawYAML, r.SpecPath); len(errs) > 0 {
			out = append(out, errs...)
		}
	}
	for _, t := range b.Tasks {
		if errs := validateOne(taskSchema, t.RawYAML, t.SpecPath); len(errs) > 0 {
			out = append(out, errs...)
		}
	}
	return out
}

func compileSchema(embedPath string) (*jsonschema.Schema, error) {
	raw, err := schemaFS.ReadFile(embedPath)
	if err != nil {
		return nil, err
	}
	doc, err := jsonschema.UnmarshalJSON(strings.NewReader(string(raw)))
	if err != nil {
		return nil, err
	}
	c := jsonschema.NewCompiler()
	c.DefaultDraft(jsonschema.Draft2020)
	if err := c.AddResource(embedPath, doc); err != nil {
		return nil, err
	}
	return c.Compile(embedPath)
}

func validateOne(sch *jsonschema.Schema, rawYAML []byte, path string) []SpecError {
	// YAML → generic map → JSON → UnmarshalJSON → Validate.
	var raw any
	if err := yaml.Unmarshal(rawYAML, &raw); err != nil {
		return []SpecError{{Path: path, Kind: "schema", Message: err.Error()}}
	}
	asJSON, err := json.Marshal(yamlToJSONCompatible(raw))
	if err != nil {
		return []SpecError{{Path: path, Kind: "schema", Message: err.Error()}}
	}
	doc, err := jsonschema.UnmarshalJSON(strings.NewReader(string(asJSON)))
	if err != nil {
		return []SpecError{{Path: path, Kind: "schema", Message: err.Error()}}
	}
	if err := sch.Validate(doc); err != nil {
		// Split multi-error messages into individual SpecErrors.
		msg := err.Error()
		return splitValidationErrors(path, msg)
	}
	return nil
}

// yamlToJSONCompatible converts yaml.v3's map[interface{}]interface{} (which
// happens for some nested structures) into map[string]interface{} suitable
// for json.Marshal.
func yamlToJSONCompatible(v any) any {
	switch x := v.(type) {
	case map[any]any:
		m := map[string]any{}
		for k, val := range x {
			m[fmt.Sprint(k)] = yamlToJSONCompatible(val)
		}
		return m
	case map[string]any:
		m := map[string]any{}
		for k, val := range x {
			m[k] = yamlToJSONCompatible(val)
		}
		return m
	case []any:
		out := make([]any, len(x))
		for i, e := range x {
			out[i] = yamlToJSONCompatible(e)
		}
		return out
	default:
		return v
	}
}

func splitValidationErrors(path, combined string) []SpecError {
	var out []SpecError
	for _, line := range strings.Split(combined, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "jsonschema validation failed") {
			continue
		}
		out = append(out, SpecError{Path: path, Kind: "schema", Message: line})
	}
	if len(out) == 0 {
		out = []SpecError{{Path: path, Kind: "schema", Message: combined}}
	}
	return out
}

func validateReferential(b *Bundle) []SpecError {
	var out []SpecError

	// Uniqueness: requirement ids.
	reqByID := map[string]*Requirement{}
	for i := range b.Requirements {
		r := &b.Requirements[i]
		if prev, dup := reqByID[r.ID]; dup {
			out = append(out, SpecError{
				Path: r.SpecPath, Kind: "duplicate",
				Message: fmt.Sprintf("requirement id %q also declared at %s", r.ID, prev.SpecPath),
			})
			continue
		}
		reqByID[r.ID] = r
	}

	// Uniqueness: gate ids within each requirement.
	gatesByID := map[string]*Gate{} // keyed globally so tasks can look them up
	for i := range b.Requirements {
		r := &b.Requirements[i]
		local := map[string]bool{}
		for j := range r.Gates {
			g := &r.Gates[j]
			if local[g.ID] {
				out = append(out, SpecError{
					Path: r.SpecPath, Kind: "duplicate",
					Message: fmt.Sprintf("gate id %q duplicated within requirement %q", g.ID, r.ID),
				})
				continue
			}
			local[g.ID] = true
			gatesByID[g.ID] = g
		}
	}

	// Uniqueness: task ids.
	taskByID := map[string]*Task{}
	for i := range b.Tasks {
		t := &b.Tasks[i]
		if prev, dup := taskByID[t.ID]; dup {
			out = append(out, SpecError{
				Path: t.SpecPath, Kind: "duplicate",
				Message: fmt.Sprintf("task id %q also declared at %s", t.ID, prev.SpecPath),
			})
			continue
		}
		taskByID[t.ID] = t
	}

	// Referential: task.implements → requirement exists.
	// Referential: task.required_gates → gate exists on implemented requirement.
	// Referential: task.depends_on → task exists + no self-ref.
	for i := range b.Tasks {
		t := &b.Tasks[i]
		implemented := map[string]bool{}
		for _, reqID := range t.Implements {
			if _, ok := reqByID[reqID]; !ok {
				out = append(out, SpecError{
					Path: t.SpecPath, Kind: "ref",
					Message: fmt.Sprintf("task %q implements unknown requirement %q", t.ID, reqID),
				})
				continue
			}
			implemented[reqID] = true
		}

		// required_gates must belong to an implemented requirement.
		for _, gateID := range t.RequiredGates {
			g, ok := gatesByID[gateID]
			if !ok {
				out = append(out, SpecError{
					Path: t.SpecPath, Kind: "ref",
					Message: fmt.Sprintf("task %q requires unknown gate %q", t.ID, gateID),
				})
				continue
			}
			// Find which requirement owns this gate.
			ownerReq := ""
			for rid, r := range reqByID {
				for j := range r.Gates {
					if &r.Gates[j] == g {
						ownerReq = rid
					}
				}
			}
			if ownerReq != "" && !implemented[ownerReq] {
				out = append(out, SpecError{
					Path: t.SpecPath, Kind: "ref",
					Message: fmt.Sprintf(
						"task %q requires gate %q which belongs to requirement %q (not in implements)",
						t.ID, gateID, ownerReq),
				})
			}
		}

		for _, dep := range t.DependsOn {
			if dep == t.ID {
				out = append(out, SpecError{
					Path: t.SpecPath, Kind: "ref",
					Message: fmt.Sprintf("task %q depends on itself", t.ID),
				})
				continue
			}
			if _, ok := taskByID[dep]; !ok {
				out = append(out, SpecError{
					Path: t.SpecPath, Kind: "ref",
					Message: fmt.Sprintf("task %q depends on unknown task %q", t.ID, dep),
				})
			}
		}
	}

	// Cycle detection on depends_on (DFS).
	out = append(out, detectCycles(b.Tasks, taskByID)...)

	return out
}

func detectCycles(tasks []Task, byID map[string]*Task) []SpecError {
	const (
		white = 0
		gray  = 1
		black = 2
	)
	color := map[string]int{}
	var out []SpecError
	var dfs func(id string, path []string)
	dfs = func(id string, path []string) {
		color[id] = gray
		t, ok := byID[id]
		if !ok {
			color[id] = black
			return
		}
		for _, dep := range t.DependsOn {
			if color[dep] == gray {
				cyclePath := append(path, id, dep)
				out = append(out, SpecError{
					Path: t.SpecPath, Kind: "cycle",
					Message: fmt.Sprintf("dependency cycle: %v", cyclePath),
				})
				continue
			}
			if color[dep] == white {
				dfs(dep, append(path, id))
			}
		}
		color[id] = black
	}
	for _, t := range tasks {
		if color[t.ID] == white {
			dfs(t.ID, nil)
		}
	}
	return out
}
