package cli

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"

	"github.com/ProductOfAmerica/cairn/internal/cairnerr"
)

// SpecInitResult is returned to the CLI envelope.
type SpecInitResult struct {
	Created     []string `json:"created"`
	Skipped     []string `json:"skipped"`
	Overwritten bool     `json:"overwritten,omitempty"`
}

// requirementTemplate is the literal body of REQ-001.yaml.example.
// First non-blank line is the marker comment that the renamed-template
// detector in internal/intent/validate.go looks for. DO NOT REWORD.
const requirementTemplate = `# cairn requirement spec template — DO NOT EDIT THIS FILE.
# This file is scaffolding. Real requirement YAML is derived
# from prose design specs by the using-cairn skill. See cairn
# plugin docs for the full flow.
#
# Fields:
#   id          — stable identifier like REQ-NNN. Must match prose section label.
#   title       — short description matching prose H1.
#   why         — motivation paragraph from prose.
#   scope_in    — list of file globs this requirement covers.
#   scope_out   — list of file globs explicitly excluded.
#   gates       — acceptance gates (see below).
#
# Gate fields:
#   id          — stable identifier like AC-NNN.
#   kind        — one of: test, property, rubric, human, custom.
#   producer    — how this gate is produced:
#     kind      — one of: executable, human, agent, pipeline.
#     config    — producer-specific config.
id: REQ-001
title: Example requirement
why: Short motivation paragraph.
scope_in: [example/**]
scope_out: []
gates:
  - id: AC-001
    kind: test
    producer:
      kind: executable
      config:
        command: [go, test, ./example/...]
        pass_on_exit_code: 0
`

// taskTemplate is the literal body of TASK-001.yaml.example.
const taskTemplate = `# cairn task spec template — DO NOT EDIT THIS FILE.
# Real task YAML is derived from prose plan docs by the
# using-cairn skill. See cairn plugin docs.
#
# Fields:
#   id              — stable identifier like TASK-NNN.
#   implements      — list of REQ ids this task contributes to.
#   depends_on      — list of TASK ids that must complete first.
#   required_gates  — list of AC gate ids that must pass for this task.
id: TASK-001
implements: [REQ-001]
depends_on: []
required_gates: [AC-001]
`

// SpecInit scaffolds <root>/requirements/REQ-001.yaml.example and
// <root>/tasks/TASK-001.yaml.example. Idempotent: existing files are
// left alone unless force=true.
func SpecInit(root string, force bool) (*SpecInitResult, error) {
	res := &SpecInitResult{Created: []string{}, Skipped: []string{}}
	for _, sub := range []string{"requirements", "tasks"} {
		dir := filepath.Join(root, sub)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, cairnerr.New(cairnerr.CodeSubstrate,
				"spec_init_mkdir_failed",
				"create spec subdirectory failed").
				WithCause(err).
				WithDetails(map[string]any{
					"path":  dir,
					"cause": err.Error(),
				})
		}
	}
	pairs := []struct {
		path string
		body string
	}{
		{filepath.Join(root, "requirements", "REQ-001.yaml.example"), requirementTemplate},
		{filepath.Join(root, "tasks", "TASK-001.yaml.example"), taskTemplate},
	}
	for _, p := range pairs {
		existing, readErr := os.ReadFile(p.path)
		if readErr == nil && !force && bytes.Equal(existing, []byte(p.body)) {
			res.Skipped = append(res.Skipped, p.path)
			continue
		}
		// All other paths (absent, read-error, content-mismatch, force=true) write.
		if err := os.WriteFile(p.path, []byte(p.body), 0o644); err != nil {
			return nil, cairnerr.New(cairnerr.CodeSubstrate,
				"spec_init_write_failed",
				"write template failed").
				WithCause(err).
				WithDetails(map[string]any{
					"path":  p.path,
					"cause": err.Error(),
				})
		}
		verify, verifyErr := os.ReadFile(p.path)
		if verifyErr != nil {
			return nil, cairnerr.New(cairnerr.CodeSubstrate,
				"spec_init_write_unverified",
				"template write did not persist on disk; inspect filesystem or sync-engine state").
				WithCause(verifyErr).
				WithDetails(map[string]any{
					"path":          p.path,
					"expected_size": len(p.body),
					"cause":         verifyErr.Error(),
				})
		}
		if !bytes.Equal(verify, []byte(p.body)) {
			wantSum := sha256.Sum256([]byte(p.body))
			gotSum := sha256.Sum256(verify)
			return nil, cairnerr.New(cairnerr.CodeSubstrate,
				"spec_init_write_unverified",
				"template write did not persist on disk; inspect filesystem or sync-engine state").
				WithDetails(map[string]any{
					"path":            p.path,
					"expected_size":   len(p.body),
					"got_size":        len(verify),
					"expected_sha256": hex.EncodeToString(wantSum[:]),
					"got_sha256":      hex.EncodeToString(gotSum[:]),
				})
		}
		res.Created = append(res.Created, p.path)
		if force {
			res.Overwritten = true
		}
	}
	return res, nil
}

// TemplatesForTest returns the canonical scaffolding bodies for
// REQ-001.yaml.example and TASK-001.yaml.example. Exposed so that
// integration tests in internal/integration can byte-compare
// disk content against the expected template body without
// duplicating the literal. The returned strings MUST be treated
// as read-only; callers must not mutate the underlying backing
// arrays.
func TemplatesForTest() (requirement, task string) {
	return requirementTemplate, taskTemplate
}
