package integration_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSpecInitE2E(t *testing.T) {
	root := t.TempDir()
	// 1. Run spec init in a fresh directory.
	out := runCLIInDir(t, root, "spec", "init", "--path", "specs")
	env := parseEnvelope(t, out)
	data := env["data"].(map[string]any)
	created := data["created"].([]any)
	if len(created) != 2 {
		t.Fatalf("created: want 2, got %d", len(created))
	}

	// 2. Verify .yaml.example files exist.
	for _, p := range []string{
		filepath.Join(root, "specs", "requirements", "REQ-001.yaml.example"),
		filepath.Join(root, "specs", "tasks", "TASK-001.yaml.example"),
	} {
		body, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("missing %s: %v", p, err)
		}
		if !strings.Contains(string(body), "DO NOT EDIT THIS FILE") {
			t.Errorf("template marker missing in %s", p)
		}
	}

	// 3. Run spec validate; specs_scanned must be 0/0 (.example files excluded).
	out2 := runCLIInDir(t, root, "spec", "validate", "--path", "specs")
	env2 := parseEnvelope(t, out2)
	data2 := env2["data"].(map[string]any)
	scanned := data2["specs_scanned"].(map[string]any)
	if scanned["requirements"] != float64(0) || scanned["tasks"] != float64(0) {
		t.Errorf("scan should ignore .example files: %v", scanned)
	}

	// 4. Re-run spec init; idempotent — no new files.
	out3 := runCLIInDir(t, root, "spec", "init", "--path", "specs")
	env3 := parseEnvelope(t, out3)
	data3 := env3["data"].(map[string]any)
	if len(data3["created"].([]any)) != 0 {
		t.Errorf("second init should create 0 files: %v", data3["created"])
	}
	if len(data3["skipped"].([]any)) != 2 {
		t.Errorf("second init should skip 2 files: %v", data3["skipped"])
	}
}
